# Use a imagem oficial do OpenJDK 17
FROM openjdk:17-jdk-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo JAR gerado pelo Maven (substitua com o nome correto do seu JAR)
COPY target/ptfBackEnd-0.0.1-SNAPSHOT.jar /app/ptfBackEnd.jar

# Exponha a porta em que o Spring Boot vai rodar (geralmente 8080)
EXPOSE 8080

# Comando para rodar a aplicação no contêiner
CMD ["java", "-jar", "ptfBackEnd.jar"]
